# 全局配置
global:
  chinese:
    enable: true
  hover:
    scale: true
  scroll_progress:
    bar: true
  busuanzi_counter:
    enable: false

# 基本信息
info:
  title: 子豪的小破站
  author: hzihhuang
  url: https://super-zihao.github.io/blog

# 默认图片
defaults:
  avatar: https://picsum.photos/300

# 顶部导航栏配置
navbar:
  auto_hide: false # 顶部是否自动隐藏
  links:
    标签:
      icon: fa-solid fa-tags
      path: /tags/
    分类:
      icon: fa-solid fa-folder
      path: /categories/
    相册:
      icon: fa-solid fa-image
      path: /masonry/
    GitHub:
      icon: fa-brands fa-github
      path: https://github.com/Super-ZiHao

# 首页
home:
  sidebar: # 侧边栏
    position: right
    announcement: 做一个温柔的人，浅浅笑，轻轻爱 # 公告
    links: # 左侧导航栏
      标签:
        icon: fa-solid fa-tags
        path: ./tags
      分类:
        icon: fa-solid fa-folder
        path: ./categories
      相册:
        icon: fa-solid fa-image
        path: ./masonry

# 首页第一屏
home_banner:
  style: fixed
  title: 愿我们想要的都得到，得到的都美好。
  subtitle:
    text: [
      '内心丰盈者，独行也如众。',
      '理想的生活需要一点热爱和心动',
      '理想主义的少年永远不会向现实招安。',
      '在人生的道路上，想哭就哭，想笑就笑吧，但是千万别忘记了赶路',
      '喜欢就争取，的到就珍惜，错过就忘记。',
      '你所期盼的都会稳稳妥妥的到来'
    ]
    typing_speed: 40
    backing_speed: 40
    starting_delay: 800 # 开始延迟（毫秒）
    backing_delay: 5000 # 退格延迟（毫秒）
    loop: true # 是否循环
    smart_backspace: true #是否智能退格
  # image: # 背景图
  #   light: ./source/images/wallhaven-wqery6-light.webp
  #   dark: ./source/images/wallhaven-wqery6-drak.webp
  social_links: # 社交
    enable: true
    links:
      [github]: https://github.com/Super-ZiHao

# 页脚
footer:
  start: 2023/8/11 17:40:14

# 评论系统
comment:
  enable: false

# 搜索
search:
  enable: false