# 全局配置
global:
  chinese:
    enable: true
  hover:
    scale: true
  scroll_progress:
    bar: true
  busuanzi_counter:
    enable: false

# 基本信息
info:
  title: 子豪的小破站
  author: hzihhuang
  url: https://super-zihao.github.io/blog

# 默认图片
defaults:
  avatar: https://picsum.photos/300

# 顶部导航栏配置
navbar:
  auto_hide: false # 顶部是否自动隐藏
  links:
    标签:
      icon: fa-solid fa-tags
      path: /tags/
    分类:
      icon: fa-solid fa-folder
      path: /categories/
    相册:
      icon: fa-solid fa-image
      path: /masonry/
    GitHub:
      icon: fa-brands fa-github
      path: https://github.com/Super-ZiHao

# 首页
home:
  sidebar: # 侧边栏
    position: right
    announcement: 天行健,君子以自强不息 # 公告
    links: # 左侧导航栏
      标签:
        icon: fa-solid fa-tags
        path: ./tags
      分类:
        icon: fa-solid fa-folder
        path: ./categories
      相册:
        icon: fa-solid fa-image
        path: ./masonry

# 首页第一屏
home_banner:
  style: fixed
  title: 祝你每天开心快乐。
  subtitle:
    text: ['内心丰盈者，独行也如众。', '理想主义的少年永远不会向现实招安。']
  # image: # 背景图
  #   light: ./source/images/wallhaven-wqery6-light.webp
  #   dark: ./source/images/wallhaven-wqery6-drak.webp
  social_links: # 社交
    enable: true
    links:
      [github]: https://github.com/Super-ZiHao

# 页脚
footer:
  start: 2023/8/11 17:40:14

# 评论系统
comment:
  enable: false

# 搜索
search:
  enable: true